#!name=Office365

#!desc=修改Office365访问时的UserAgent

#!icon=https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Microsoft_365_%282022%29.svg/512px-Microsoft_365_%282022%29.svg.png

#!author=Jack Yang



[Script]
Office365 = type=http-request, pattern=^https:\/\/outlook\.office[365]*\.com\/, requires-body=0, script-path=https://raw.githubusercontent.com/yangwudong/Quantumult-X/refs/heads/main/SS/scripts/office365.js

[MITM]
hostname = %APPEND% outlook.office365.com, outlook.office.com