#!name=Pillow

#!desc=Pillow解锁会员

#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/pillow.png


#!author=Jack Yang



[Script]

Pillow=type=http-response,pattern=^https:\/\/api\.(revenuecat|rc-backup)\.com\/.+\/(receipts$|subscribers\/?(.*?)*$),requires-body=1 ,script-path=https://raw.githubusercontent.com/yangwudong/Quantumult-X/refs/heads/main/SS/scripts/pillow.js

[MITM]

hostname = %APPEND% api.revenuecat.com, api.rc-backup.com